### ISSUE TITLE
Running project as ConsoleApp causes RTE in UserDataTuple component.

### ISSUE THREAD

**Issue by bsumirak** [NeuroBox3D/VRL-NeuroBox-Plugin#28]
Steps to reproduce:
- open hh-project template
- `export as console app`
- call run.sh inside console app folder

```
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at eu.mihosoft.vrl.system.VSessionRunner.runMain(VSessionRunner.java:251)
    at eu.mihosoft.vrl.system.VSessionRunner.run(VSessionRunner.java:181)
    at eu.mihosoft.vrl.system.VSessionRunner$run.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
    at eu.mihosoft.vrl.user.VSessionMainClass.main(VSessionMainClass.groovy:10)
Caused by: java.lang.RuntimeException: UserDataTuple: no data stored at position 0 of tuple.
    at edu.gcsc.vrl.userdata.UserDataTuple.getData(UserDataTuple.java:60)
    at edu.gcsc.vrl.neurobox.membrane_transport.cable.Hodgkin_Huxley.create(Hodgkin_Huxley.java:45)
    at edu.gcsc.vrl.neurobox.membrane_transport.cable.Hodgkin_Huxley$create.call(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
    at eu.mihosoft.vrl.user.Main.run(Main.groovy:46)
    ... 11 more
```

Probably similar to #27.

**Comment by bsumirak** [comment]
Implementation of getModelAsCode in UserDependentSubsetModel fixed this.
Console app seems to work now (having fixed #27, too).
